// Xcode 27 refuses IPHONEOS_DEPLOYMENT_TARGET below 15.0. Three transitive pods still ship
// a pre-15 target of their own that overrides the Podfile's `platform :ios, '15.1'`
// (RNCAsyncStorage-RNCAsyncStorage_resources: 13.4; SDWebImage-SDWebImage: 9.0;
// react-native-maps-ReactNativeMapsPrivacy: 11.0). A rebuild on macOS 27 fails
// immediately with "The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is
// set to 13.4, but the range of supported deployment target versions is 15.0 to 27.0.x."
//
// Fix: append a post_install hook that walks every pod target and forces the deployment
// target to 15.1. Because `ios/` is regenerated by `expo prebuild`, the hook has to live in
// a config plugin, not in a hand-edited Podfile. Reproducer + evidence in
// `dev/test-plan-auth.md` Run 5 (library@main).
const { withDangerousMod } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

const SENTINEL = "# @kupkop/ios-deployment-target-bump";
const IOS_TARGET = "15.1";

// The generated Podfile has exactly one `post_install do |installer|` inside the app
// target; we splice our loop in just before its terminating `end` (the first two-space
// indented `end` after the marker — the target's own `end` is unindented). If the RN
// template shape changes and the marker is missing, we bail out rather than corrupt the
// file — the failure is loud (the build still errors as it did before), not silent.
function patch(contents) {
  if (contents.includes(SENTINEL)) return contents;
  const marker = "post_install do |installer|";
  const markerAt = contents.indexOf(marker);
  if (markerAt < 0) return contents;
  const closeAt = contents.indexOf("\n  end\n", markerAt);
  if (closeAt < 0) return contents;
  const bump =
    "\n" +
    "    " + SENTINEL + "\n" +
    "    installer.pods_project.targets.each do |t|\n" +
    "      t.build_configurations.each do |c|\n" +
    "        c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '" + IOS_TARGET + "'\n" +
    "      end\n" +
    "    end";
  return contents.slice(0, closeAt) + bump + contents.slice(closeAt);
}

module.exports = function withIosDeploymentTarget(config) {
  return withDangerousMod(config, [
    "ios",
    async (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, "Podfile");
      const before = fs.readFileSync(podfile, "utf8");
      const after = patch(before);
      if (after !== before) fs.writeFileSync(podfile, after);
      return cfg;
    },
  ]);
};

module.exports.patch = patch;
module.exports.SENTINEL = SENTINEL;
